version: '3.7'
services:
  web:
    build:
      context: .
    image: webhook_deploy:${GIT_COMMIT:-latest}
    command: bin/run-dev
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app:delegated
