site_name: Dokku Webhook Deploy
repo_url: https://github.com/pmac/dokku-webhook-deploy
theme: readthedocs
edit_uri: ""

nav:
  - Home: index.md
  - Config Options: config.md

markdown_extensions:
  - toc:
      permalink: true
